// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixazzsarbwlzxigwjelf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4YXp6c2FyYndsenhpZ3dqZWxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzY2NDcsImV4cCI6MjA2OTIxMjY0N30.oHO_s8tBLmmGIFjPyqDPuM6Q05AzDkNzYEArYqwOKsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});